site_name: Pig Eyes DIY
site_url: https://ocampco.github.io/pig-eyes-diy
site_description: Resource for Toyota/Toyopet Mark II, Chaser, Cresta and Cressida
site_author: ocampco

theme:
  name: material
  palette:
    primary: white
    accent: pink
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  logo: ./assets/logo.png
  favicon: ./assets/logo.png

extra_css:
  - ./assets/extra.css

markdown_extensions:
  - toc:
      permalink: '&#128279;'
      permalink_class: 'toc-permalink-override'
      toc_depth: '2-3'
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - admonition
  - pymdownx.details

plugins:
  - section-index
  - git-revision-date

nav:
  - Home: index.md
  - Suspension:
    - ./suspension/index.md
    - 'Front Coilovers': ./suspension/front-coilovers.md
    - 'Steering Arms': ./suspension/steering-arms.md
    - 'Rear Shocks': ./suspension/rear-shocks.md
    - 'Rear Springs': ./suspension/rear-springs.md
  - Exterior:
    - ./exterior/index.md
  - Electronics:
    - ./electronics/index.md
    - Dashboard: ./electronics/dashboard.md
    - Wiring: ./electronics/wiring.md
  - Interior:
    - ./interior/index.md
    - Seats: ./interior/seats.md
  - 'Wheel and Tyre':
    - ./wheel-and-tyre/index.md
    - Tyres: ./wheel-and-tyre/tyres.md
